name: Publish package to npmjs

on:
  push:
    branches:
      - main
      - fix/**
      - feat/**
      - breaking/**
    paths-ignore:
      - .github/**
      - test/**
  workflow_dispatch:
    inputs:
      skip:
        description: 'Skip tests'
        type: boolean
        default: false
        required: false

permissions:
  id-token: write # Required for OIDC
  contents: write

concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  build:
    name: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org
      - name: Replace branch name in branches array
        run: sed -i "s|'current-branch'|'${{ github.ref_name }}'|" .releaserc.yaml
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        if: github.event.inputs.skip != 'true'
        run: yarn test:coverage
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v6
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
